apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-terraform
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Luviz/dev-aks.git
    targetRevision: main
    path: gitops/terraform-runner
  destination:
    server: https://kubernetes.default.svc
    namespace: gitops-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
