{{- if .Values.gitopsApps.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitops-apps
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "argocd-apps.labels" . | nindent 4 }}
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: {{ .Values.repoURL | quote }}
    targetRevision: {{ .Values.targetRevision }}
    path: {{ .Values.gitopsApps.path }}
  destination:
    server: https://kubernetes.default.svc
    namespace: {{ .Values.gitopsApps.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
{{- end }}
